# Generated by Django 5.2.10 on 2026-03-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower number = higher priority'),
        ),
    ]
