# Generated by Django 5.2.10 on 2026-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turf_is_popular_turf_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='priority',
            field=models.IntegerField(default=1, help_text='Lower number = higher priority'),
        ),
    ]
