# Generated by Django 4.2.10 on 2026-04-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_turf_retire'),
    ]

    operations = [
    ]
